// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Patient struct {
	ID              int64
	PharmacyID      int64
	FirstName       string
	LastName        string
	Phone           string
	Email           string
	DeliveryAddress string
	Fulfillment     string
	Notes           string
	Consensus       bool
	ConsensusDate   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Pharmacy struct {
	ID        int64
	Name      string
	Address   string
	Phone     string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	Role         string
	PharmacyID   pgtype.Int8
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
