// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	Role         string
	PharmacyID   pgtype.Int8
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
