// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patients.sql

package db

import (
	"context"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (pharmacy_id, first_name, last_name, phone, email, delivery_address, fulfillment, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, pharmacy_id, first_name, last_name, phone, email, delivery_address, fulfillment, notes, consensus, consensus_date, created_at, updated_at
`

type CreatePatientParams struct {
	PharmacyID      int64
	FirstName       string
	LastName        string
	Phone           string
	Email           string
	DeliveryAddress string
	Fulfillment     string
	Notes           string
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.PharmacyID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.DeliveryAddress,
		arg.Fulfillment,
		arg.Notes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.DeliveryAddress,
		&i.Fulfillment,
		&i.Notes,
		&i.Consensus,
		&i.ConsensusDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, pharmacy_id, first_name, last_name, phone, email, delivery_address, fulfillment, notes, consensus, consensus_date, created_at, updated_at
FROM patients
WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id int64) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.DeliveryAddress,
		&i.Fulfillment,
		&i.Notes,
		&i.Consensus,
		&i.ConsensusDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatientsByPharmacy = `-- name: ListPatientsByPharmacy :many
SELECT id, first_name, last_name, phone, email, consensus
FROM patients
WHERE pharmacy_id = $1::BIGINT
ORDER BY last_name, first_name
`

type ListPatientsByPharmacyRow struct {
	ID        int64
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Consensus bool
}

func (q *Queries) ListPatientsByPharmacy(ctx context.Context, pharmacyID int64) ([]ListPatientsByPharmacyRow, error) {
	rows, err := q.db.Query(ctx, listPatientsByPharmacy, pharmacyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsByPharmacyRow
	for rows.Next() {
		var i ListPatientsByPharmacyRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Consensus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPatientConsensus = `-- name: SetPatientConsensus :exec
UPDATE patients
SET consensus = true, consensus_date = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetPatientConsensus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setPatientConsensus, id)
	return err
}

const updatePatient = `-- name: UpdatePatient :exec
UPDATE patients
SET first_name = $2, last_name = $3, phone = $4, email = $5, delivery_address = $6, fulfillment = $7, notes = $8, updated_at = now()
WHERE id = $1
`

type UpdatePatientParams struct {
	ID              int64
	FirstName       string
	LastName        string
	Phone           string
	Email           string
	DeliveryAddress string
	Fulfillment     string
	Notes           string
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.Exec(ctx, updatePatient,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.DeliveryAddress,
		arg.Fulfillment,
		arg.Notes,
	)
	return err
}
