// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pharmacies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPharmacy = `-- name: CreatePharmacy :one
INSERT INTO pharmacies (name, address, phone, email)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, phone, email, created_at, updated_at
`

type CreatePharmacyParams struct {
	Name    string
	Address string
	Phone   string
	Email   string
}

func (q *Queries) CreatePharmacy(ctx context.Context, arg CreatePharmacyParams) (Pharmacy, error) {
	row := q.db.QueryRow(ctx, createPharmacy,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	var i Pharmacy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPharmacyByID = `-- name: GetPharmacyByID :one
SELECT id, name, address, phone, email, created_at, updated_at
FROM pharmacies
WHERE id = $1
`

func (q *Queries) GetPharmacyByID(ctx context.Context, id int64) (Pharmacy, error) {
	row := q.db.QueryRow(ctx, getPharmacyByID, id)
	var i Pharmacy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPharmacies = `-- name: ListPharmacies :many
SELECT
    p.id,
    p.name,
    p.address,
    p.phone,
    p.email,
    p.created_at,
    p.updated_at,
    COUNT(DISTINCT u.id)::BIGINT AS personnel_count
FROM pharmacies p
LEFT JOIN users u ON u.pharmacy_id = p.id
GROUP BY p.id
ORDER BY p.name
`

type ListPharmaciesRow struct {
	ID             int64
	Name           string
	Address        string
	Phone          string
	Email          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PersonnelCount int64
}

func (q *Queries) ListPharmacies(ctx context.Context) ([]ListPharmaciesRow, error) {
	rows, err := q.db.Query(ctx, listPharmacies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPharmaciesRow
	for rows.Next() {
		var i ListPharmaciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PersonnelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePharmacy = `-- name: UpdatePharmacy :exec
UPDATE pharmacies
SET name = $2, address = $3, phone = $4, email = $5, updated_at = now()
WHERE id = $1
`

type UpdatePharmacyParams struct {
	ID      int64
	Name    string
	Address string
	Phone   string
	Email   string
}

func (q *Queries) UpdatePharmacy(ctx context.Context, arg UpdatePharmacyParams) error {
	_, err := q.db.Exec(ctx, updatePharmacy,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	return err
}
