// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prescriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (patient_id, medication_name, units_per_box, daily_consumption, box_start_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, patient_id, medication_name, units_per_box, daily_consumption, box_start_date, created_at, updated_at
`

type CreatePrescriptionParams struct {
	PatientID        int64
	MedicationName   string
	UnitsPerBox      int32
	DailyConsumption pgtype.Numeric
	BoxStartDate     pgtype.Date
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, createPrescription,
		arg.PatientID,
		arg.MedicationName,
		arg.UnitsPerBox,
		arg.DailyConsumption,
		arg.BoxStartDate,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.MedicationName,
		&i.UnitsPerBox,
		&i.DailyConsumption,
		&i.BoxStartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrescriptionByID = `-- name: GetPrescriptionByID :one
SELECT id, patient_id, medication_name, units_per_box, daily_consumption, box_start_date, created_at, updated_at
FROM prescriptions
WHERE id = $1
`

func (q *Queries) GetPrescriptionByID(ctx context.Context, id int64) (Prescription, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByID, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.MedicationName,
		&i.UnitsPerBox,
		&i.DailyConsumption,
		&i.BoxStartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefillHistory = `-- name: InsertRefillHistory :exec
INSERT INTO refill_history (prescription_id, box_start_date, box_end_date)
VALUES ($1, $2, $3)
`

type InsertRefillHistoryParams struct {
	PrescriptionID int64
	BoxStartDate   pgtype.Date
	BoxEndDate     pgtype.Date
}

func (q *Queries) InsertRefillHistory(ctx context.Context, arg InsertRefillHistoryParams) error {
	_, err := q.db.Exec(ctx, insertRefillHistory, arg.PrescriptionID, arg.BoxStartDate, arg.BoxEndDate)
	return err
}

const listPrescriptionsByPatient = `-- name: ListPrescriptionsByPatient :many
SELECT id, patient_id, medication_name, units_per_box, daily_consumption, box_start_date, created_at, updated_at
FROM prescriptions
WHERE patient_id = $1
ORDER BY medication_name
`

func (q *Queries) ListPrescriptionsByPatient(ctx context.Context, patientID int64) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.MedicationName,
			&i.UnitsPerBox,
			&i.DailyConsumption,
			&i.BoxStartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrescription = `-- name: UpdatePrescription :exec
UPDATE prescriptions
SET medication_name = $2, units_per_box = $3, daily_consumption = $4, box_start_date = $5, updated_at = now()
WHERE id = $1
`

type UpdatePrescriptionParams struct {
	ID               int64
	MedicationName   string
	UnitsPerBox      int32
	DailyConsumption pgtype.Numeric
	BoxStartDate     pgtype.Date
}

func (q *Queries) UpdatePrescription(ctx context.Context, arg UpdatePrescriptionParams) error {
	_, err := q.db.Exec(ctx, updatePrescription,
		arg.ID,
		arg.MedicationName,
		arg.UnitsPerBox,
		arg.DailyConsumption,
		arg.BoxStartDate,
	)
	return err
}
